	<? include "header.phtml"; ?>
	  <h1><?=$this->escape($this->title);?></h1>
	  <h2><?=$this->escape($this->description);?></h2>
	  <a href="register">Register</a>
	  <table border="1">
	    <tr>
	      <th>ID</th>
	      <th>User Name</th>     
	      <th>First Name</th>    
	      <th>Last Name</th>     
	      <th>Action</th>    
	    </tr>
	  <? 
// There is no function 'result()' 
// like codeIgniter to use 'foreach()' function 
		$datas = $this->datas;
	    for($i = 1; $i<= count($datas);$i++){ ?>
	    <tr>
	      <td><?=$datas[$i]['id']?></td> 
	      <td><?=$datas[$i]['user_name']?></td>
	      <td><?=$datas[$i]['first_name']?></td>   
	      <td><?=$datas[$i]['last_name']?></td>    
	      <td>
	        <a href="edit/id/<?=$datas[$i]['id']?>">Edit</a>
	        |
	        <a href="del/id/<?=$datas[$i]['id']?>">Delete</a>    
	      </td>    
	    </tr>
	  <? } ?>
	  </table>
	   
	<? include "footer.phtml"; ?>