<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="./public/skins/blues/css/style.css" media="all" rel="stylesheet" type="text/css" />
        <link href="./public/skins/blues/css/layout.css" media="all" rel="stylesheet" type="text/css" />
        <?php echo $this->loadSkin($this->skin);?>
    </head>
    <body>
    <div id="pageWrapper">
        <div id="header">
            <p>#header</p>
        </div>
        <div id="nav">
            <p>#nav</p>
        </div>
        <div id="sidebar">
            <div id="subNav">
                <p>#subNav</p>
            </div>
            <div id="adminMenu">
                <p>#adminMenu</p>
            </div>
            <div id="userForm">
                <p>#userForm</p>
            </div>
                <p>#sidebar</p>
        </div>
        <div id="main">
                <p>#main</p>
        </div>
        <div id="footer">
            <p>#footer</p>
        </div>
    </div>
    </body>
</html>
    
    
    
    